### ISSUE TITLE
Can't click the users in a pod under pod details.

### ISSUE THREAD

**Issue by dillfrescott** [positive-intentions/chat#117]
It throws this error:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'blockchain')
TypeError: Cannot read properties of undefined (reading 'blockchain')
    at https://chat.positive-intentions.com/290.main.js:5826:7
    at https://chat.positive-intentions.com/516.main.js:109687:28
    at a (https://chat.positive-intentions.com/516.main.js:138102:204)
    at https://chat.positive-intentions.com/516.main.js:138102:420
    at Object.Zh [as useSyncExternalStore] (https://chat.positive-intentions.com/961.main.js:172:35)
    at https://chat.positive-intentions.com/540.main.js:32:309
    at https://chat.positive-intentions.com/516.main.js:138102:489
    at useSelector2 (https://chat.positive-intentions.com/516.main.js:109694:27)
    at Profile (https://chat.positive-intentions.com/290.main.js:5823:58)
    at Nh (https://chat.positive-intentions.com/961.main.js:166:137)
  ```

**Comment by xoron** [comment]
thanks for pointing that out! i'll take a look

**Comment by dillfrescott** [comment]
Okay! Thx!
